SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE,"%Y-%m-%d") as "출판일"
FROM BOOK B 
JOIN AUTHOR A
ON B.AUTHOR_ID =A.AUTHOR_ID
WHERE CATEGORY = '경제'
order by DATE_FORMAT(B.PUBLISHED_DATE,"%Y-%m-%d");